# -*- Mode: makefile -*-
# RISC-V specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/riscv64
TESTS += test-div
TESTS += noexec

# Disable compressed instructions for test-noc
TESTS += test-noc
test-noc: LDFLAGS = -nostdlib -static
run-test-noc: QEMU_OPTS += -cpu rv64,c=false

TESTS += test-aes
run-test-aes: QEMU_OPTS += -cpu rv64,zk=on

# Test for fcvtmod
TESTS += test-fcvtmod
test-fcvtmod: CFLAGS += -march=rv64imafdc
test-fcvtmod: LDFLAGS += -static
run-test-fcvtmod: QEMU_OPTS += -cpu rv64,d=true,zfa=true

TESTS += test-ame-misc
run-test-ame-misc: QEMU_OPTS += -cpu rv64,xsmtame=true,xsmtame-version=0.6

TESTS += test-ame-mmacc
run-test-ame-mmacc: QEMU_OPTS += \
    -cpu rv64,f=true,d=true,xsmtame=true,xsmtame-version=0.6,ame_tlen=1024,ame_trlen=32
